swagger: "2.0"
info:
  version: 0.1.0
  title: Authoritah Certificate Authority
host: localhost:8000
basePath: /v0
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /info:
    get:
      summary: Information about the certificate authority
      operationId: info
      tags:
        - information
      responses:
        "200":
          description: Information about the certificate authority
          schema:
            $ref: "#/definitions/CertificateAuthority"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
  /init:
    post:
      summary: Initializes a new certificate authority
      operationId: init
      tags:
        - configuration
      requestBody:
        description: Certificate authority profile
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/CertificateAuthority'
      responses:
        "200":
          description: Certificate authority successfully initialized
          schema:
            $ref: "#/definitions/CertificateAuthority"
        "409":
          description: Certificate authority already initialized
          schema:
            $ref: "#/definitions/Error"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
definitions:
  CertificateAuthority:
    type: "object"
    required:
      - commonName
    properties:
      commonName:
        type: string
  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
      message:
        type: string